remote_theme: aljazceru/hacker-gh-pages-theme
plugins:
- jekyll-remote-theme

show_downloads: false
google_analytics: G-3GMHKJW916
plausible_script_url: https://analytics.cypherpunk.cloud/js/script.js
plausible: ungovernable.tech
